apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdm-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /mdm-openapi
            - name: BASE_URL
              value: /mdm-openapi-ui
